### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by darkdarcool** [cursorweb/14th-Birthday-Project#1]
Happy birthday dude! Hope you have a good one! (Mines in a week, but let’s not talk about that lol)

**Comment by cursorweb** [comment]
thanks!! :D
Also happy early birthday to you too!

**Comment by darkdarcool** [comment]
Thanks!!

**Comment by darkdarcool** [comment]
Don’t think I’ll do anything for it, at least in replit, but eh, y’ah never know
